name: Continious Integration
           
on: [push, workflow_dispatch]

jobs:
  build:
    uses: ./.github/workflows/build.yml

  unit-test:
    needs: build
    uses: ./.github/workflows/unit-test.yml

  publish:
    needs: build
    uses: ./.github/workflows/publish.yml

  full-cycle-test:
    needs: publish
    uses: ./.github/workflows/full-cycle-test.yml
      


  



